export const ROUTE_NAME_MAIN = 'Main';

export const ROUTE_NAME_SUPPORT = 'ROUTE_NAME_SUPPORT';
export const ROUTE_NAME_QMS = 'ROUTE_NAME_QMS';
export const ROUTE_NAME_LABOR_COSTS = 'ROUTE_NAME_LABOR_COSTS';
export const ROUTE_NAME_ACCOUNTING = 'ROUTE_NAME_ACCOUNTING';

export const ROUTE_NAME_LABOR_COSTS_DEPARTMENT = 'ROUTE_LABOR_COSTS_DEPARTMENT';
export const ROUTE_NAME_INTERNAL_TEST_ANALYSIS = 'ROUTE_NAME_INTERNAL_TEST_ANALYSIS';
export const  ROUTE_NAME_TEST_ANALYSIS = 'ROUTE_NAME_TEST_ANALYSIS';
export const  ROUTE_NAME_APPLICATIONS_PERFORMANCE_EVALUATION = 'ROUTE_NAME_APPLICATIONS_PERFORMANCE_EVALUATION';
export const  ROUTE_NAME_EFFECTIVENESS_PROCESS = 'ROUTE_NAME_EFFECTIVENESS_PROCESS';
