export const ROUTE_NAME_MAIN = 'Main';

export const ROUTE_NAME_SUPPORT = 'ROUTE_NAME_SUPPORT';
export const ROUTE_NAME_QMS = 'ROUTE_NAME_QMS';
export const ROUTE_NAME_LABOR_COSTS = 'ROUTE_NAME_LABOR_COSTS';


export const ROUTE_NAME_LABOR_COSTS_DEPARTMENT = 'ROUTE_LABOR_COSTS_DEPARTMENT';

export const ROUTE_NAME_ACCOUNTING = 'ROUTE_NAME_ACCOUNTING';

export const ROUTE_NAME_ACCOUNTING_PROJECT_LIST = "ROUTE_NAME_ACCOUNTING_PROJECT_LIST";
export const ROUTE_NAME_ACCOUNTING_2 = "ROUTE_NAME_ACCOUNTING_2";
export const ROUTE_NAME_ACCOUNTING_BY_DEPARTMENTS = "ROUTE_NAME_ACCOUNTING_BY_DEPARTMENTS";

export const ROUTE_NAME_LABOR_COSTS_UNDERVALUED_ISSUES = "ROUTE_NAME_LABOR_COSTS_UNDERVALUED_ISSUES";