export const ROUTE_NAME_MAIN = 'Main';

// Трудозатраты
export const ROUTE_NAME_LABOR_COSTS = {
  MAIN: 'ROUTE_NAME_LABOR_COSTS',
  DEPARTMENT: 'ROUTE_LABOR_COSTS_DEPARTMENT',
  USS: 'ROUTE_LABOR_USS',
  MANAGEMENT_EMPLOYEES: 'ROUTE_NAME_MANAGEMENT_EMPLOYEES',
  DESIGN: 'ROUTE_NAME_LABOR_COSTS_DESIGN',
  PROJECT: 'ROUTE_LABOR_COSTS_PROJECT',
  UNDERVALUED_ISSUES: 'ROUTE_NAME_LABOR_COSTS_UNDERVALUED_ISSUES',
} as const;

// СМК
export const ROUTE_NAME_QMS = {
  MAIN: 'ROUTE_NAME_QMS',
  INTERNAL_TEST_ANALYSIS: 'ROUTE_NAME_INTERNAL_TEST_ANALYSIS',
  TEST_ANALYSIS: 'ROUTE_NAME_TEST_ANALYSIS',
  APPLICATIONS_PERFORMANCE_EVALUATION: 'ROUTE_NAME_APPLICATIONS_PERFORMANCE_EVALUATION',
  EFFECTIVENESS_PROCESS: 'ROUTE_NAME_EFFECTIVENESS_PROCESS',
} as const;

// Бухгалтерия
export const ROUTE_NAME_ACCOUNTING = {
  MAIN: 'ROUTE_NAME_ACCOUNTING',
  PROJECT_LIST: 'ROUTE_NAME_ACCOUNTING_PROJECT_LIST',
  _2: 'ROUTE_NAME_ACCOUNTING_2',
  BY_DEPARTMENTS: 'ROUTE_NAME_ACCOUNTING_BY_DEPARTMENTS',
} as const;

//Сопровождение
export const ROUTE_NAME_SUPPORT = {
  MAIN: 'ROUTE_NAME_SUPPORT',
  ANALYSIS_TASK_STATUS_CHANGES: 'ROUTE_NAME_ANALYSIS_TASK_STATUS_CHANGES',
  DONE_TASKS_BY_PERIOD: 'ROUTE_NAME_DONE_TASKS_BY_PERIOD',
  EXTRA_TASKS_BY_DATE: 'ROUTE_NAME_ANAROUTE_NAME_EXTRA_TASKS_BY_DATELYSIS_TASK_STATUS_CHANGES',
  ANALYSIS_TASKS: 'ROUTE_NAME_ANALYSIS_TASKS',
  TASKS_RETURNED_AND_RECEIVED_FOR_ONE_PERIOD:
    'ROUTE_NAME_TASKS_RETURNED_AND_RECEIVED_FOR_ONE_PERIOD',
  ANALYSIS_TASK_STATUS_CHANGESTASKS_RETURNED_AND_RECEIVED_AS_UNFULFILLED_FOR_ONE_PERIOD:
    'ROUTE_NAME_ANALYSIS_TASK_STATUS_CHANGESTASKS_RETURNED_AND_RECEIVED_AS_UNFULFILLED_FOR_ONE_PERIOD',
  TASKS_RETURNED_FOR_REVISION_BY_PERIOD: 'ROUTE_NAME_TASKS_RETURNED_FOR_REVISION_BY_PERIOD',
  TASKS_EXTRA_PERIOD: 'ROUTE_NAME_TASKS_EXTRA_PERIOD',
  DEADLINE_CONTROL_SUPPORT_TASKS_EXECUTION: 'ROUTE_NAME_DEADLINE_CONTROL_SUPPORT_TASKS_EXECUTION',
  UNFULFILLED_REQUESTS_FOR: 'ROUTE_NAME_UNFULFILLED_REQUESTS_FOR',
  UNFULFILLED_REQUESTS_ON_APPRECIATED_AND_UNAPPRECIATED:
    'ROUTE_NAME_UNFULFILLED_REQUESTS_ON_APPRECIATED_AND_UNAPPRECIATED',
  ACT_OF_SUPPORT_BIB: 'ROUTE_NAME_ACT_OF_SUPPORT_BIB',
  TASKS_EXTRA_BY_DATE: 'ROUTE_NAME_TASKS_EXTRA_BY_DATE',
  TESTING: 'ROUTE_NAME_TESTING',
  RECEIVED_TASKS_BY_PERIOD: 'ROUTE_NAROUTE_NAME_RECEIVED_TASKS_BY_PERIODME_ACT_OF_SUPPORT_BIB',
} as const;
