/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton/BaseButton.vue')['default']
    BaseChip: typeof import('./components/BaseChip/BaseChip.vue')['default']
    BaseField: typeof import('./components/BaseField/BaseField.vue')['default']
    BaseFieldset: typeof import('./components/BaseFieldset/BaseFieldset.vue')['default']
    BaseForm: typeof import('./components/BaseForm/BaseForm.vue')['default']
    BaseSelect: typeof import('./components/BaseSelect/BaseSelect.vue')['default']
    BaseTitle: typeof import('./components/BaseTitle/BaseTitle.vue')['default']
    DatePeriod: typeof import('./components/DatePeriod/DatePeriod.vue')['default']
    DatePeriodActivator: typeof import('./components/DatePeriod/DatePeriodActivator.vue')['default']
    DatePeriodButton: typeof import('./components/DatePeriod/DatePeriodButton.vue')['default']
    DatePeriodDropdown: typeof import('./components/DatePeriod/DatePeriodDropdown.vue')['default']
    DatePeriodItem: typeof import('./components/DatePeriod/DatePeriodItem.vue')['default']
    DropDown: typeof import('./components/DropDown/DropDown.vue')['default']
    FieldWrapper: typeof import('./components/FieldWrapper/FieldWrapper.vue')['default']
    HorizontalList: typeof import('./components/HorizontalList/HorizontalList.vue')['default']
    LabeledField: typeof import('./components/LabeledField/LabeledField.vue')['default']
    ListLinkItem: typeof import('./components/ListLinkItem/ListLinkItem.vue')['default']
    NavLink: typeof import('./components/NavLink/NavLink.vue')['default']
    OptionControl: typeof import('./components/OptionControl/OptionControl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StringButton: typeof import('./components/StringButton/StringButton.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/SvgIcon.vue')['default']
    TabButton: typeof import('./components/TabButton/TabButton.vue')['default']
    TabList: typeof import('./components/TabList/TabList.vue')['default']
    TabListItem: typeof import('./components/TabList/TabListItem.vue')['default']
    TitledContent: typeof import('./components/TitledContent/TitledContent.vue')['default']
    VerticalList: typeof import('./components/VerticalList/VerticalList.vue')['default']
    VueScrollbar: typeof import('./components/VueScrollbar/VueScrollbar.vue')['default']
  }
}
